### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by JIzabal** [leiandrade/cse15l-lab-reports#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
- [x] All relevant code examples written with backticks (```)
  - Commands, java files, and other code should be written with backticks
- [x] All screenshots correspond to the described steps
- [x] All titles of sections are formatted as headers or similar
- [x] Lab report is on its own page, not the index page
- [x] Last example counts keystrokes and shows how to run remotely saving time
  - Fix the last step so that the command copies and runs the code on the remote server: Part 7 – Making Remote Running Even More Pleasant (this is from the lab in week 1) - Use what you’ve learned to come up with the most pleasant process you can for making a local edit to WhereAmI.java, then copying it to the remote server and running it.
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by leiandrade** [comment]
Hello, could you explain how I could count keystrokes? In our lab 1, we used examples from the lab to do.

**Comment by JIzabal** [comment]
Of course! After making an edit, we want you to run a command that copies your java file to your remote server (i.e., Not on your machine), compiles it on the remote server, and then runs it on the remote server. Check out Part 5 in Lab 1 to see how to copy a file over to a remote server, and then look at Part 7 to see how to run a command on the remote server. Once you figure out how to do those things, you can combine multiple commands using semicolons to create one long command that copies your file to the remote server, compiles it there, and runs it there. After running that command once, you can click the up key on your keyboard to see it again and click enter to run it. Consider how many keystrokes this takes (i.e., How many times you press a button on your keyboard and click the mouse), and that should be what you write down. Let me know if you have any more questions!

**Comment by leiandrade** [comment]
hi! I edited both of the tasks that I needed from the feedback. Would I just go straight into resubmitting for a regrade on Gradescope or do you need to see it first?

**Comment by JIzabal** [comment]
You're good to submit a regrade request! Great work! One thing to keep in mind is that the number of keystrokes is greater than 2. Assuming that you had run these commands before, than running them again would take 5 keystrokes. You'd need to press the <kbd>up</kbd> key twice and then <kbd>enter</kbd> once to run the `scp` command, and then you'd need to press the <kbd>up</kbd> key once and then <kbd>enter</kbd> once to run the command that compiles and runs the file remotely.
